### ISSUE TITLE
你好，搜不到这个插件？谢谢

### ISSUE THREAD

**Issue by DelmarHuang** [qcrao/block-share-card#1]

**Comment by qcrao** [comment]
感谢关注，还没上架呢。上架之后我会来这里告知。

**Comment by DelmarHuang** [comment]
好的 谢谢

**Comment by qcrao** [comment]
@DelmarHuang 已经上线到 Roam Depot 了，搜索 share 可直达扩展。

<img width="1208" alt="image" src="https://github.com/qcrao/block-share-card/assets/7698088/62759185-2d16-4d64-8828-3428ba4732c6">

**Comment by DelmarHuang** [comment]
> @DelmarHuang 已经上线到 Roam Depot 了，搜索 share 可直达扩展。
> 
> <img alt="image" width="1208" src="https://private-user-images.githubusercontent.com/7698088/339192826-62759185-2d16-4d64-8828-3428ba4732c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjI3MTYsIm5iZiI6MTcxODM2MjQxNiwicGF0aCI6Ii83Njk4MDg4LzMzOTE5MjgyNi02Mjc1OTE4NS0yZDE2LTRkNjQtODgyOC0zNDI4YmE0NzMyYzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTRUMTA1MzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDIxOTMyNWE3MTJhYzExMmRiZTk2OGVjYzhkZmNlN2YyNTExYzAyZDAwMWI3Y2ZhZTY4ZTExNDg1NjExYWYxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qtIQA4B0msX8ODrBeCCya8j1lDOHqHB50nMJtU3NGTk">

感谢！非常好用！
